import { DrinkCatalogItem, DrinkCategory } from '../models/types';

// Drink colors by category (alphabetically sorted)
export const CATEGORY_COLORS = {
  beer: '#F59E0B',       // Amber
  cocktails: '#3B82F6',  // Blue
  longdrinks: '#10B981', // Emerald/Teal
  spirits: '#EC4899',    // Pink
  wine: '#8B5CF6',       // Purple
} as const;

// Category display names and icons (alphabetically sorted)
export const CATEGORY_INFO: Record<DrinkCategory, { name: string; icon: string }> = {
  beer: { name: 'Beer', icon: 'beer-outline' },
  cocktails: { name: 'Cocktails', icon: 'cafe-outline' },
  longdrinks: { name: 'Long Drinks', icon: 'pint-outline' },
  spirits: { name: 'Spirits', icon: 'flask-outline' },
  wine: { name: 'Wine', icon: 'wine-outline' },
};

// Full drink catalog organized by category (alphabetically sorted)
// Categories: Beer, Cocktails, Long Drinks, Spirits, Wine
// Drinks within each category are sorted alphabetically by name
export const DRINK_CATALOG: DrinkCatalogItem[] = [
  // ========== BEER (9 items, alphabetically sorted) ==========
  {
    id: 'beer_large',
    name: 'Beer (Large)',
    category: 'beer',
    volumeMl: 500,
    volumeOz: 16,
    abvPercent: 5.0,
    icon: 'beer',
    color: CATEGORY_COLORS.beer,
  },
  {
    id: 'beer_small',
    name: 'Beer (Small)',
    category: 'beer',
    volumeMl: 330,
    volumeOz: 12,
    abvPercent: 5.0,
    icon: 'beer-outline',
    color: CATEGORY_COLORS.beer,
  },
  {
    id: 'beer_craft',
    name: 'Craft Beer',
    category: 'beer',
    volumeMl: 330,
    volumeOz: 12,
    abvPercent: 6.5,
    icon: 'beer-outline',
    color: CATEGORY_COLORS.beer,
  },
  {
    id: 'beer_ipa',
    name: 'IPA',
    category: 'beer',
    volumeMl: 330,
    volumeOz: 12,
    abvPercent: 6.5,
    icon: 'beer-outline',
    color: CATEGORY_COLORS.beer,
  },
  {
    id: 'beer_light',
    name: 'Light Beer',
    category: 'beer',
    volumeMl: 330,
    volumeOz: 12,
    abvPercent: 3.5,
    icon: 'beer-outline',
    color: CATEGORY_COLORS.beer,
  },
  {
    id: 'beer_pint',
    name: 'Pint',
    category: 'beer',
    volumeMl: 568,
    volumeOz: 20,
    abvPercent: 5.0,
    icon: 'beer',
    color: CATEGORY_COLORS.beer,
  },
  {
    id: 'beer_radler',
    name: 'Radler / Shandy',
    category: 'beer',
    volumeMl: 500,
    volumeOz: 16,
    abvPercent: 2.5,
    icon: 'beer-outline',
    color: CATEGORY_COLORS.beer,
  },
  {
    id: 'beer_stout',
    name: 'Stout',
    category: 'beer',
    volumeMl: 440,
    volumeOz: 16,
    abvPercent: 4.5,
    icon: 'beer',
    color: CATEGORY_COLORS.beer,
  },
  {
    id: 'beer_wheat',
    name: 'Wheat Beer',
    category: 'beer',
    volumeMl: 500,
    volumeOz: 16,
    abvPercent: 5.4,
    icon: 'beer',
    color: CATEGORY_COLORS.beer,
  },

  // ========== COCKTAILS (16 items, alphabetically sorted) ==========
  {
    id: 'aperol_spritz',
    name: 'Aperol Spritz',
    category: 'cocktails',
    volumeMl: 150,
    volumeOz: 5,
    abvPercent: 11.0,
    icon: 'wine-outline',
    color: CATEGORY_COLORS.cocktails,
  },
  {
    id: 'bloody_mary',
    name: 'Bloody Mary',
    category: 'cocktails',
    volumeMl: 45,
    volumeOz: 1.5,
    abvPercent: 40.0,
    icon: 'cafe-outline',
    color: CATEGORY_COLORS.cocktails,
  },
  {
    id: 'caipirinha',
    name: 'Caipirinha',
    category: 'cocktails',
    volumeMl: 60,
    volumeOz: 2,
    abvPercent: 40.0,
    icon: 'cafe-outline',
    color: CATEGORY_COLORS.cocktails,
  },
  {
    id: 'cosmopolitan',
    name: 'Cosmopolitan',
    category: 'cocktails',
    volumeMl: 60,
    volumeOz: 2,
    abvPercent: 40.0,
    icon: 'cafe-outline',
    color: CATEGORY_COLORS.cocktails,
  },
  {
    id: 'daiquiri',
    name: 'Daiquiri',
    category: 'cocktails',
    volumeMl: 60,
    volumeOz: 2,
    abvPercent: 40.0,
    icon: 'cafe-outline',
    color: CATEGORY_COLORS.cocktails,
  },
  {
    id: 'espresso_martini',
    name: 'Espresso Martini',
    category: 'cocktails',
    volumeMl: 60,
    volumeOz: 2,
    abvPercent: 40.0,
    icon: 'cafe-outline',
    color: CATEGORY_COLORS.cocktails,
  },
  {
    id: 'long_island_iced_tea',
    name: 'Long Island Iced Tea',
    category: 'cocktails',
    volumeMl: 80,
    volumeOz: 2.5,
    abvPercent: 40.0,
    icon: 'cafe-outline',
    color: CATEGORY_COLORS.cocktails,
  },
  {
    id: 'mai_tai',
    name: 'Mai Tai',
    category: 'cocktails',
    volumeMl: 60,
    volumeOz: 2,
    abvPercent: 40.0,
    icon: 'cafe-outline',
    color: CATEGORY_COLORS.cocktails,
  },
  {
    id: 'manhattan',
    name: 'Manhattan',
    category: 'cocktails',
    volumeMl: 75,
    volumeOz: 2.5,
    abvPercent: 40.0,
    icon: 'cafe-outline',
    color: CATEGORY_COLORS.cocktails,
  },
  {
    id: 'margarita',
    name: 'Margarita',
    category: 'cocktails',
    volumeMl: 60,
    volumeOz: 2,
    abvPercent: 40.0,
    icon: 'cafe-outline',
    color: CATEGORY_COLORS.cocktails,
  },
  {
    id: 'mojito',
    name: 'Mojito',
    category: 'cocktails',
    volumeMl: 60,
    volumeOz: 2,
    abvPercent: 40.0,
    icon: 'cafe-outline',
    color: CATEGORY_COLORS.cocktails,
  },
  {
    id: 'moscow_mule',
    name: 'Moscow Mule',
    category: 'cocktails',
    volumeMl: 50,
    volumeOz: 1.5,
    abvPercent: 40.0,
    icon: 'cafe-outline',
    color: CATEGORY_COLORS.cocktails,
  },
  {
    id: 'negroni',
    name: 'Negroni',
    category: 'cocktails',
    volumeMl: 90,
    volumeOz: 3,
    abvPercent: 40.0,
    icon: 'cafe-outline',
    color: CATEGORY_COLORS.cocktails,
  },
  {
    id: 'old_fashioned',
    name: 'Old Fashioned',
    category: 'cocktails',
    volumeMl: 60,
    volumeOz: 2,
    abvPercent: 40.0,
    icon: 'cafe-outline',
    color: CATEGORY_COLORS.cocktails,
  },
  {
    id: 'pina_colada',
    name: 'Piña Colada',
    category: 'cocktails',
    volumeMl: 60,
    volumeOz: 2,
    abvPercent: 40.0,
    icon: 'cafe-outline',
    color: CATEGORY_COLORS.cocktails,
  },
  {
    id: 'sex_on_the_beach',
    name: 'Sex on the Beach',
    category: 'cocktails',
    volumeMl: 60,
    volumeOz: 2,
    abvPercent: 40.0,
    icon: 'cafe-outline',
    color: CATEGORY_COLORS.cocktails,
  },
  {
    id: 'tequila_sunrise',
    name: 'Tequila Sunrise',
    category: 'cocktails',
    volumeMl: 45,
    volumeOz: 1.5,
    abvPercent: 40.0,
    icon: 'cafe-outline',
    color: CATEGORY_COLORS.cocktails,
  },
  {
    id: 'whiskey_sour',
    name: 'Whiskey Sour',
    category: 'cocktails',
    volumeMl: 50,
    volumeOz: 1.5,
    abvPercent: 40.0,
    icon: 'cafe-outline',
    color: CATEGORY_COLORS.cocktails,
  },

  // ========== LONG DRINKS (10 items, alphabetically sorted) ==========
  {
    id: 'longdrink_bacardi_cola',
    name: 'Bacardi Cola',
    category: 'longdrinks',
    volumeMl: 40,
    volumeOz: 1.5,
    abvPercent: 40.0,
    icon: 'pint-outline',
    color: CATEGORY_COLORS.longdrinks,
  },
  {
    id: 'longdrink_captain_cola',
    name: 'Captain Morgan & Cola',
    category: 'longdrinks',
    volumeMl: 40,
    volumeOz: 1.5,
    abvPercent: 35.0,
    icon: 'pint-outline',
    color: CATEGORY_COLORS.longdrinks,
  },
  {
    id: 'longdrink_cuba_libre',
    name: 'Cuba Libre',
    category: 'longdrinks',
    volumeMl: 40,
    volumeOz: 1.5,
    abvPercent: 40.0,
    icon: 'pint-outline',
    color: CATEGORY_COLORS.longdrinks,
  },
  {
    id: 'longdrink_gin_tonic',
    name: 'Gin Tonic',
    category: 'longdrinks',
    volumeMl: 50,
    volumeOz: 1.5,
    abvPercent: 40.0,
    icon: 'pint-outline',
    color: CATEGORY_COLORS.longdrinks,
  },
  {
    id: 'longdrink_jack_cola',
    name: 'Jack & Coke',
    category: 'longdrinks',
    volumeMl: 40,
    volumeOz: 1.5,
    abvPercent: 40.0,
    icon: 'pint-outline',
    color: CATEGORY_COLORS.longdrinks,
  },
  {
    id: 'longdrink_generic',
    name: 'Long Drink',
    category: 'longdrinks',
    volumeMl: 40,
    volumeOz: 1.5,
    abvPercent: 40.0,
    icon: 'pint-outline',
    color: CATEGORY_COLORS.longdrinks,
  },
  {
    id: 'longdrink_vodka_bull',
    name: 'Vodka Bull',
    category: 'longdrinks',
    volumeMl: 40,
    volumeOz: 1.5,
    abvPercent: 40.0,
    icon: 'pint-outline',
    color: CATEGORY_COLORS.longdrinks,
  },
  {
    id: 'longdrink_vodka_energy',
    name: 'Vodka Energy',
    category: 'longdrinks',
    volumeMl: 40,
    volumeOz: 1.5,
    abvPercent: 40.0,
    icon: 'pint-outline',
    color: CATEGORY_COLORS.longdrinks,
  },
  {
    id: 'longdrink_vodka_orange',
    name: 'Vodka Orange',
    category: 'longdrinks',
    volumeMl: 40,
    volumeOz: 1.5,
    abvPercent: 40.0,
    icon: 'pint-outline',
    color: CATEGORY_COLORS.longdrinks,
  },
  {
    id: 'longdrink_whiskey_cola',
    name: 'Whiskey Cola',
    category: 'longdrinks',
    volumeMl: 40,
    volumeOz: 1.5,
    abvPercent: 40.0,
    icon: 'pint-outline',
    color: CATEGORY_COLORS.longdrinks,
  },

  // ========== SPIRITS (11 items, alphabetically sorted) ==========
  {
    id: 'spirits_aperol',
    name: 'Aperol',
    category: 'spirits',
    volumeMl: 60,
    volumeOz: 2,
    abvPercent: 11.0,
    icon: 'flask-outline',
    color: CATEGORY_COLORS.spirits,
  },
  {
    id: 'spirits_baileys',
    name: 'Baileys / Cream Liqueur',
    category: 'spirits',
    volumeMl: 50,
    volumeOz: 1.5,
    abvPercent: 17.0,
    icon: 'flask-outline',
    color: CATEGORY_COLORS.spirits,
  },
  {
    id: 'spirits_brandy',
    name: 'Brandy / Cognac',
    category: 'spirits',
    volumeMl: 40,
    volumeOz: 1.5,
    abvPercent: 40.0,
    icon: 'flask-outline',
    color: CATEGORY_COLORS.spirits,
  },
  {
    id: 'gin',
    name: 'Gin',
    category: 'spirits',
    volumeMl: 40,
    volumeOz: 1.5,
    abvPercent: 40.0,
    icon: 'flask-outline',
    color: CATEGORY_COLORS.spirits,
  },
  {
    id: 'spirits_jagermeister',
    name: 'Jägermeister',
    category: 'spirits',
    volumeMl: 40,
    volumeOz: 1.5,
    abvPercent: 35.0,
    icon: 'flask-outline',
    color: CATEGORY_COLORS.spirits,
  },
  {
    id: 'rum',
    name: 'Rum',
    category: 'spirits',
    volumeMl: 40,
    volumeOz: 1.5,
    abvPercent: 40.0,
    icon: 'flask-outline',
    color: CATEGORY_COLORS.spirits,
  },
  {
    id: 'spirits_sambuca',
    name: 'Sambuca',
    category: 'spirits',
    volumeMl: 40,
    volumeOz: 1.5,
    abvPercent: 38.0,
    icon: 'flask-outline',
    color: CATEGORY_COLORS.spirits,
  },
  {
    id: 'shot',
    name: 'Shot',
    category: 'spirits',
    volumeMl: 40,
    volumeOz: 1.5,
    abvPercent: 40.0,
    icon: 'flask-outline',
    color: CATEGORY_COLORS.spirits,
  },
  {
    id: 'tequila',
    name: 'Tequila',
    category: 'spirits',
    volumeMl: 40,
    volumeOz: 1.5,
    abvPercent: 40.0,
    icon: 'flask-outline',
    color: CATEGORY_COLORS.spirits,
  },
  {
    id: 'vodka',
    name: 'Vodka',
    category: 'spirits',
    volumeMl: 40,
    volumeOz: 1.5,
    abvPercent: 40.0,
    icon: 'flask-outline',
    color: CATEGORY_COLORS.spirits,
  },
  {
    id: 'whiskey',
    name: 'Whiskey',
    category: 'spirits',
    volumeMl: 40,
    volumeOz: 1.5,
    abvPercent: 40.0,
    icon: 'flask-outline',
    color: CATEGORY_COLORS.spirits,
  },

  // ========== WINE (8 items, alphabetically sorted) ==========
  {
    id: 'wine_champagne',
    name: 'Champagne',
    category: 'wine',
    volumeMl: 125,
    volumeOz: 4,
    abvPercent: 12.5,
    icon: 'wine',
    color: CATEGORY_COLORS.wine,
  },
  {
    id: 'wine_mulled',
    name: 'Mulled Wine / Glühwein',
    category: 'wine',
    volumeMl: 200,
    volumeOz: 6,
    abvPercent: 10.0,
    icon: 'wine',
    color: CATEGORY_COLORS.wine,
  },
  {
    id: 'wine_port',
    name: 'Port Wine',
    category: 'wine',
    volumeMl: 75,
    volumeOz: 2.5,
    abvPercent: 20.0,
    icon: 'wine',
    color: CATEGORY_COLORS.wine,
  },
  {
    id: 'wine_prosecco',
    name: 'Prosecco',
    category: 'wine',
    volumeMl: 125,
    volumeOz: 4,
    abvPercent: 11.0,
    icon: 'wine',
    color: CATEGORY_COLORS.wine,
  },
  {
    id: 'wine_red',
    name: 'Red Wine',
    category: 'wine',
    volumeMl: 150,
    volumeOz: 5,
    abvPercent: 13.0,
    icon: 'wine-outline',
    color: CATEGORY_COLORS.wine,
  },
  {
    id: 'wine_rose',
    name: 'Rosé Wine',
    category: 'wine',
    volumeMl: 150,
    volumeOz: 5,
    abvPercent: 12.0,
    icon: 'wine-outline',
    color: CATEGORY_COLORS.wine,
  },
  {
    id: 'wine_sparkling',
    name: 'Sparkling Wine',
    category: 'wine',
    volumeMl: 125,
    volumeOz: 4,
    abvPercent: 12.0,
    icon: 'wine',
    color: CATEGORY_COLORS.wine,
  },
  {
    id: 'wine_white',
    name: 'White Wine',
    category: 'wine',
    volumeMl: 150,
    volumeOz: 5,
    abvPercent: 12.0,
    icon: 'wine-outline',
    color: CATEGORY_COLORS.wine,
  },
];

// Helper to get drink by ID
export function getDrinkById(id: string): DrinkCatalogItem | undefined {
  return DRINK_CATALOG.find(d => d.id === id);
}

// Helper to get drinks by category
export function getDrinksByCategory(category: DrinkCategory): DrinkCatalogItem[] {
  return DRINK_CATALOG.filter(d => d.category === category);
}

// Helper to search drinks by name
export function searchDrinks(query: string): DrinkCatalogItem[] {
  const lowerQuery = query.toLowerCase().trim();
  if (!lowerQuery) return DRINK_CATALOG;

  return DRINK_CATALOG.filter(d =>
    d.name.toLowerCase().includes(lowerQuery)
  );
}

// All categories for filter chips (alphabetically sorted)
export const ALL_CATEGORIES: DrinkCategory[] = ['beer', 'cocktails', 'longdrinks', 'spirits', 'wine'];

// Default color for custom drinks
export const CUSTOM_DRINK_COLOR = '#6B7280';
export const CUSTOM_DRINK_ICON = 'create-outline';
