/**
 * BAC (Blood Alcohol Concentration) unit conversion utilities
 *
 * Internal storage: Permille (‰) - e.g., 0.5‰
 * Display options:
 *   - permille: Same as internal (0.5‰)
 *   - percent: Divide by 10 (0.05%)
 *
 * Conversion: 1‰ = 0.1% (or 1% = 10‰)
 *
 * Examples:
 *   US legal limit: 0.08% = 0.8‰
 *   German limit: 0.5‰ = 0.05%
 */

export type BACUnit = 'permille' | 'percent';

// Conversion factors
export const PERMILLE_TO_PERCENT = 0.1; // 1‰ = 0.1%
export const PERCENT_TO_PERMILLE = 10;   // 1% = 10‰

/**
 * Convert permille to percent
 * @param permille BAC value in permille (e.g., 0.5)
 * @returns BAC value in percent (e.g., 0.05)
 */
export function permilleToPercent(permille: number): number {
  return permille * PERMILLE_TO_PERCENT;
}

/**
 * Convert percent to permille
 * @param percent BAC value in percent (e.g., 0.08)
 * @returns BAC value in permille (e.g., 0.8)
 */
export function percentToPermille(percent: number): number {
  return percent * PERCENT_TO_PERMILLE;
}

/**
 * Convert BAC from internal permille to display unit
 * @param bacPermille BAC value in permille (internal storage)
 * @param unit Target display unit
 * @returns BAC value in target unit
 */
export function bacForDisplay(bacPermille: number, unit: BACUnit): number {
  if (unit === 'percent') {
    return permilleToPercent(bacPermille);
  }
  return bacPermille;
}

/**
 * Convert BAC from display unit to internal permille
 * @param bacValue BAC value in display unit
 * @param unit Source display unit
 * @returns BAC value in permille (internal storage)
 */
export function bacToPermille(bacValue: number, unit: BACUnit): number {
  if (unit === 'percent') {
    return percentToPermille(bacValue);
  }
  return bacValue;
}

/**
 * Get the unit symbol for display
 */
export function getBACUnitSymbol(unit: BACUnit): string {
  return unit === 'percent' ? '%' : '‰';
}

/**
 * Get decimal places for formatting based on unit
 * Standard: 2 decimal places for both units
 */
export function getBACDecimalPlaces(unit: BACUnit): number {
  return 2;
}

/**
 * Format BAC value for display with appropriate precision
 * @param bacPermille BAC value in permille (internal storage)
 * @param unit Display unit
 * @returns Formatted string without unit symbol
 */
export function formatBACValue(bacPermille: number, unit: BACUnit): string {
  const displayValue = bacForDisplay(bacPermille, unit);
  const decimals = getBACDecimalPlaces(unit);
  return displayValue.toFixed(decimals);
}

/**
 * Format BAC value with unit symbol for display
 * @param bacPermille BAC value in permille (internal storage)
 * @param unit Display unit
 * @returns Formatted string with unit symbol (e.g., "0.05%" or "0.50‰")
 */
export function formatBACWithUnit(bacPermille: number, unit: BACUnit): string {
  return `${formatBACValue(bacPermille, unit)}${getBACUnitSymbol(unit)}`;
}

/**
 * Get the valid BAC input range for a unit (for pickers/validation)
 * Internal max is typically 3.0‰ (0.3%)
 */
export function getBACRange(unit: BACUnit): { min: number; max: number; step: number } {
  if (unit === 'percent') {
    return { min: 0.01, max: 0.30, step: 0.01 };
  }
  return { min: 0.1, max: 3.0, step: 0.1 };
}

/**
 * Generate array of BAC values for picker based on unit
 */
export function generateBACPickerValues(unit: BACUnit): { value: number; label: string }[] {
  const range = getBACRange(unit);
  const items: { value: number; label: string }[] = [];
  const decimals = getBACDecimalPlaces(unit);

  // Calculate number of steps to avoid floating point issues
  const numSteps = Math.round((range.max - range.min) / range.step) + 1;

  for (let i = 0; i < numSteps; i++) {
    const value = range.min + (i * range.step);
    // Round to avoid floating point precision issues
    const roundedValue = Math.round(value * 1000) / 1000;
    items.push({
      value: roundedValue,
      label: roundedValue.toFixed(decimals),
    });
  }

  return items;
}

/**
 * Convert a picker value to permille for storage
 * @param pickerValue Value selected from picker (in display unit)
 * @param unit Current display unit
 * @returns Value in permille for storage
 */
export function pickerValueToPermille(pickerValue: number, unit: BACUnit): number {
  return bacToPermille(pickerValue, unit);
}

/**
 * Convert a stored permille value to picker value
 * @param permilleValue Value in permille (from storage)
 * @param unit Current display unit
 * @returns Value for display in picker, rounded to match picker item precision
 */
export function permilleToPickerValue(permilleValue: number, unit: BACUnit): number {
  const rawValue = bacForDisplay(permilleValue, unit);
  // Round to 3 decimal places to exactly match values generated by generateBACPickerValues.
  // Without this, floating-point arithmetic (e.g. 0.3 * 0.1 = 0.030000000000000002)
  // produces values that fail strict === comparison inside the WheelPicker, causing it
  // to fall back to the first item (0.01).
  return Math.round(rawValue * 1000) / 1000;
}

/**
 * Validate if a BAC value is within valid range for a unit
 */
export function isValidBAC(value: number, unit: BACUnit): boolean {
  const range = getBACRange(unit);
  return value >= range.min && value <= range.max;
}

/**
 * Clamp a BAC value to the valid range for a unit
 */
export function clampBAC(value: number, unit: BACUnit): number {
  const range = getBACRange(unit);
  return Math.max(range.min, Math.min(range.max, value));
}

/**
 * Get common presets for BAC limits based on unit
 * These represent typical limits people might set
 * Labels show only the number without unit symbol
 */
export function getBACPresets(unit: BACUnit): { value: number; label: string }[] {
  if (unit === 'percent') {
    return [
      { value: 0.03, label: '0.03' },
      { value: 0.05, label: '0.05' },
      { value: 0.08, label: '0.08' },
    ];
  }
  // Permille presets
  return [
    { value: 0.3, label: '0.30' },
    { value: 0.5, label: '0.50' },
    { value: 0.8, label: '0.80' },
  ];
}
